build(deps): bump the integration-flink group in /integration/flink with 19 updates (#4235)
* build(deps): bump the integration-flink group

Bumps the integration-flink group in /integration/flink with 19 updates:

| Package | From | To |
| --- | --- | --- |
| [io.micrometer:micrometer-core](https://github.com/micrometer-metrics/micrometer) | `1.14.4` | `1.16.1` |
| [org.projectlombok:lombok](https://github.com/projectlombok/lombok) | `1.18.36` | `1.18.42` |
| [org.apache.httpcomponents.client5:httpclient5](https://github.com/apache/httpcomponents-client) | `5.4.2` | `5.6` |
| [org.junit:junit-bom](https://github.com/junit-team/junit-framework) | `5.11.4` | `6.0.1` |
| [org.testcontainers:mockserver](https://github.com/testcontainers/testcontainers-java) | `1.20.4` | `1.21.4` |
| [org.testcontainers:junit-jupiter](https://github.com/testcontainers/testcontainers-java) | `1.20.4` | `1.21.4` |
| org.apache.logging.log4j:log4j-slf4j-impl | `2.24.3` | `2.25.3` |
| [org.assertj:assertj-core](https://github.com/assertj/assertj) | `3.27.3` | `3.27.6` |
| [org.junit.jupiter:junit-jupiter](https://github.com/junit-team/junit-framework) | `5.11.4` | `6.0.1` |
| [org.junit.jupiter:junit-jupiter-params](https://github.com/junit-team/junit-framework) | `5.11.4` | `6.0.1` |
| [org.awaitility:awaitility](https://github.com/awaitility/awaitility) | `4.2.2` | `4.3.0` |
| com.google.protobuf | `0.9.4` | `0.9.6` |
| [org.apache.flink:flink-connector-kafka](https://github.com/apache/flink-connector-kafka) | `4.0.0-2.0` | `4.0.1-2.0` |
| [org.scala-lang:scala-library](https://github.com/scala/scala) | `2.12.7` | `2.13.18` |
| org.apache.kafka:kafka-clients | `3.9.0` | `4.1.1` |
| [org.testcontainers:kafka](https://github.com/testcontainers/testcontainers-java) | `1.20.5` | `1.21.4` |
| [commons-codec:commons-codec](https://github.com/apache/commons-codec) | `1.18.0` | `1.20.0` |
| [org.jetbrains.kotlinx:kotlinx-serialization-json](https://github.com/Kotlin/kotlinx.serialization) | `1.8.0` | `1.9.0` |
| [plugin.serialization](https://github.com/JetBrains/kotlin) | `2.1.10` | `2.3.0` |


Updates `io.micrometer:micrometer-core` from 1.14.4 to 1.16.1
- [Release notes](https://github.com/micrometer-metrics/micrometer/releases)
- [Commits](https://github.com/micrometer-metrics/micrometer/compare/v1.14.4...v1.16.1)

Updates `org.projectlombok:lombok` from 1.18.36 to 1.18.42
- [Changelog](https://github.com/projectlombok/lombok/blob/master/doc/changelog.markdown)
- [Commits](https://github.com/projectlombok/lombok/compare/v1.18.36...v1.18.42)

Updates `org.apache.httpcomponents.client5:httpclient5` from 5.4.2 to 5.6
- [Changelog](https://github.com/apache/httpcomponents-client/blob/master/RELEASE_NOTES.txt)
- [Commits](https://github.com/apache/httpcomponents-client/compare/rel/v5.4.2...rel/v5.6)

Updates `org.junit:junit-bom` from 5.11.4 to 6.0.1
- [Release notes](https://github.com/junit-team/junit-framework/releases)
- [Commits](https://github.com/junit-team/junit-framework/compare/r5.11.4...r6.0.1)

Updates `org.testcontainers:mockserver` from 1.20.4 to 1.21.4
- [Release notes](https://github.com/testcontainers/testcontainers-java/releases)
- [Changelog](https://github.com/testcontainers/testcontainers-java/blob/main/CHANGELOG.md)
- [Commits](https://github.com/testcontainers/testcontainers-java/compare/1.20.4...1.21.4)

Updates `org.testcontainers:junit-jupiter` from 1.20.4 to 1.21.4
- [Release notes](https://github.com/testcontainers/testcontainers-java/releases)
- [Changelog](https://github.com/testcontainers/testcontainers-java/blob/main/CHANGELOG.md)
- [Commits](https://github.com/testcontainers/testcontainers-java/compare/1.20.4...1.21.4)

Updates `org.testcontainers:junit-jupiter` from 1.20.4 to 1.21.4
- [Release notes](https://github.com/testcontainers/testcontainers-java/releases)
- [Changelog](https://github.com/testcontainers/testcontainers-java/blob/main/CHANGELOG.md)
- [Commits](https://github.com/testcontainers/testcontainers-java/compare/1.20.4...1.21.4)

Updates `org.apache.logging.log4j:log4j-slf4j-impl` from 2.24.3 to 2.25.3

Updates `org.assertj:assertj-core` from 3.27.3 to 3.27.6
- [Release notes](https://github.com/assertj/assertj/releases)
- [Commits](https://github.com/assertj/assertj/compare/assertj-build-3.27.3...assertj-build-3.27.6)

Updates `org.junit.jupiter:junit-jupiter` from 5.11.4 to 6.0.1
- [Release notes](https://github.com/junit-team/junit-framework/releases)
- [Commits](https://github.com/junit-team/junit-framework/compare/r5.11.4...r6.0.1)

Updates `org.junit.jupiter:junit-jupiter-params` from 5.11.4 to 6.0.1
- [Release notes](https://github.com/junit-team/junit-framework/releases)
- [Commits](https://github.com/junit-team/junit-framework/compare/r5.11.4...r6.0.1)

Updates `org.junit.jupiter:junit-jupiter-params` from 5.11.4 to 6.0.1
- [Release notes](https://github.com/junit-team/junit-framework/releases)
- [Commits](https://github.com/junit-team/junit-framework/compare/r5.11.4...r6.0.1)

Updates `org.awaitility:awaitility` from 4.2.2 to 4.3.0
- [Changelog](https://github.com/awaitility/awaitility/blob/master/changelog.txt)
- [Commits](https://github.com/awaitility/awaitility/compare/awaitility-4.2.2...awaitility-4.3.0)

Updates `com.google.protobuf` from 0.9.4 to 0.9.6

Updates `org.apache.flink:flink-connector-kafka` from 4.0.0-2.0 to 4.0.1-2.0
- [Commits](https://github.com/apache/flink-connector-kafka/commits)

Updates `org.scala-lang:scala-library` from 2.12.7 to 2.13.18
- [Release notes](https://github.com/scala/scala/releases)
- [Commits](https://github.com/scala/scala/compare/v2.12.7...v2.13.18)

Updates `org.apache.kafka:kafka-clients` from 3.9.0 to 4.1.1

Updates `org.testcontainers:kafka` from 1.20.5 to 1.21.4
- [Release notes](https://github.com/testcontainers/testcontainers-java/releases)
- [Changelog](https://github.com/testcontainers/testcontainers-java/blob/main/CHANGELOG.md)
- [Commits](https://github.com/testcontainers/testcontainers-java/compare/1.20.5...1.21.4)

Updates `commons-codec:commons-codec` from 1.18.0 to 1.20.0
- [Changelog](https://github.com/apache/commons-codec/blob/master/RELEASE-NOTES.txt)
- [Commits](https://github.com/apache/commons-codec/compare/rel/commons-codec-1.18.0...rel/commons-codec-1.20.0)

Updates `org.jetbrains.kotlinx:kotlinx-serialization-json` from 1.8.0 to 1.9.0
- [Release notes](https://github.com/Kotlin/kotlinx.serialization/releases)
- [Changelog](https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md)
- [Commits](https://github.com/Kotlin/kotlinx.serialization/compare/v1.8.0...v1.9.0)

Updates `plugin.serialization` from 2.1.10 to 2.3.0
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.1.10...v2.3.0)

---
updated-dependencies:
- dependency-name: io.micrometer:micrometer-core
  dependency-version: 1.16.1
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.projectlombok:lombok
  dependency-version: 1.18.42
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: integration-flink
- dependency-name: org.apache.httpcomponents.client5:httpclient5
  dependency-version: '5.6'
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.junit:junit-bom
  dependency-version: 6.0.1
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: integration-flink
- dependency-name: org.testcontainers:mockserver
  dependency-version: 1.21.4
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.testcontainers:junit-jupiter
  dependency-version: 1.21.4
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.testcontainers:junit-jupiter
  dependency-version: 1.21.4
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
  dependency-version: 2.25.3
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.assertj:assertj-core
  dependency-version: 3.27.6
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: integration-flink
- dependency-name: org.junit.jupiter:junit-jupiter
  dependency-version: 6.0.1
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: integration-flink
- dependency-name: org.junit.jupiter:junit-jupiter-params
  dependency-version: 6.0.1
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: integration-flink
- dependency-name: org.junit.jupiter:junit-jupiter-params
  dependency-version: 6.0.1
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: integration-flink
- dependency-name: org.awaitility:awaitility
  dependency-version: 4.3.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: com.google.protobuf
  dependency-version: 0.9.6
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: integration-flink
- dependency-name: org.apache.flink:flink-connector-kafka
  dependency-version: 4.0.1-2.0
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: integration-flink
- dependency-name: org.scala-lang:scala-library
  dependency-version: 2.13.18
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.apache.kafka:kafka-clients
  dependency-version: 4.1.1
  dependency-type: direct:production
  update-type: version-update:semver-major
  dependency-group: integration-flink
- dependency-name: org.testcontainers:kafka
  dependency-version: 1.21.4
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: commons-codec:commons-codec
  dependency-version: 1.20.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: org.jetbrains.kotlinx:kotlinx-serialization-json
  dependency-version: 1.9.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
- dependency-name: plugin.serialization
  dependency-version: 2.3.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: integration-flink
...

Signed-off-by: dependabot[bot] <support@github.com>

* Revert Kotlin and JUnit versions for Java 8 compatibility

- Revert Kotlin plugin from 2.3.0 to 2.1.10 (Kotlin 2.3.0 doesn't support language version 1.8)
- Revert kotlinx-serialization-json from 1.9.0 to 1.8.0
- Revert JUnit from 6.0.2 to 5.11.4 (JUnit 6.x requires Java 11+)

Java 8 compatibility is required for this project.

Signed-off-by: Maciej Obuchowski <maciej.obuchowski@datadoghq.com>

* Fix Kafka 4.1 API compatibility in Flink 2.0 tests

Update KafkaSourceTestEnv to use new Kafka 4.1 API for listing consumer group offsets.
The topicPartitions() method was removed from ListConsumerGroupOffsetsOptions in Kafka 4.0.

Changes:
- Add import for ListConsumerGroupOffsetsSpec
- Use new batched API: Admin.listConsumerGroupOffsets(Map<String, ListConsumerGroupOffsetsSpec>)
- Update setupCommittedOffsets() to use the new API pattern

This fixes the compilation error when using kafka-clients 4.1.1.

Signed-off-by: Maciej Obuchowski <maciej.obuchowski@datadoghq.com>

* fix: use Scala 2.12 for Flink 2.0 compatibility

Flink 2.0-preview1 components are compiled for Scala 2.12 (flink-table-planner_2.12).
The GenTraversableOnce trait was removed in Scala 2.13, causing NoClassDefFoundError.
Changed scalaLibraryVersion from 2.13.18 to 2.12.20 to match Flink 2.0 requirements.

Signed-off-by: Maciej Obuchowski <maciej.obuchowski@datadoghq.com>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Maciej Obuchowski <maciej.obuchowski@datadoghq.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Maciej Obuchowski <maciej.obuchowski@datadoghq.com>